name       : ckb
version    : 0.4.2
release    : 10
source     :
    - https://github.com/ckb-next/ckb-next/archive/v0.4.2.tar.gz : 75b6908d5590c293dee8258a83d4ebe206306d3df9f867596e953ef7c6a86440
license    : GPL-2.0-only
component  : desktop.core
summary    : an open-source driver for Corsair keyboards and mice
description: |
    an open-source driver for Corsair keyboards and mice
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-only-mouse-buttons-on-the-mouse-device.patch
    %patch -p1 < $pkgfiles/0001-Don-t-enable-keys-we-don-t-need-in-uinput.patch
    mkdir build && cd build
    %cmake -DDISABLE_UPDATER=1 -DFORCE_INIT_SYSTEM="systemd" -DUDEV_RULE_DIRECTORY="%libdir%/udev/rules.d/" ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    # Safety symlink
    ln -s /usr/lib/systemd/systemd/ckb-next-daemon.service $installdir/usr/lib/systemd/system/ckb-daemon.service
    rm -rf $installdir/etc/
