name       : ckb
version    : 0.2.8
release    : 3
source     :
    - git|https://github.com/mattanger/ckb-next.git : 45d18850948522a0b30099f8591b74e5d6c6bbcf
license    : GPL-2.0
component  : desktop.core
summary    : an open-source driver for Corsair keyboards and mice
description: |
    an open-source driver for Corsair keyboards and mice
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %qmake -r ckb.pro
build      : |
    %make
install    : |
    install -D -m 00755 bin/ckb $installdir/usr/share/ckb/ckb
    install -D -m 00755 bin/ckb-daemon $installdir/usr/share/ckb/ckb-daemon
    install -d $installdir/usr/share/ckb/ckb-animations
    cp bin/ckb-animations/* $installdir/usr/share/ckb/ckb-animations

    install -d $installdir/usr/bin
    ln -s /usr/share/ckb/ckb $installdir/usr/bin/ckb
    ln -s /usr/share/ckb/ckb-daemon $installdir/usr/bin/ckb-daemon
  
    install -D -m 00644 usr/ckb.png $installdir/usr/share/icons/hicolor/512x512/apps/ckb.png
    install -D -m 00644 usr/ckb.desktop $installdir/usr/share/applications/ckb.desktop
    install -D -m 00644 service/systemd/ckb-daemon.service $installdir/usr/lib/systemd/system/ckb-daemon.service
