name       : ckb
version    : 0.4.0
release    : 8
source     :
    - https://github.com/ckb-next/ckb-next/archive/v0.4.0.tar.gz : 5521c5a94e87ba035c6d9340e37785fa6f29710215f3e3201bb6949c88de8bd1
license    : GPL-2.0-only
component  : desktop.core
summary    : an open-source driver for Corsair keyboards and mice
description: |
    an open-source driver for Corsair keyboards and mice
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %patch -p1 < $pkgfiles/0001-We-use-systemd-don-t-check-for-this-file.patch
    mkdir build && cd build
    %cmake -DDISABLE_UPDATER=1 ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    # Safety symlink
    ln -s /usr/lib/systemd/systemd/ckb-next-daemon.service $installdir/usr/lib/systemd/system/ckb-daemon.service
    # Put udev bits in right place
    install -Dm00644 linux/udev/99-ckb-next-daemon.rules $installdir%libdir%/udev/rules.d/99-ckb-daemon.rules
    rm -rf $installdir/etc/
