name       : ckb
version    : 0.3.1
release    : 6
source     :
    - git|https://github.com/ckb-next/ckb-next.git : v0.3.1
license    : GPL-2.0-only
component  : desktop.core
summary    : an open-source driver for Corsair keyboards and mice
description: |
    an open-source driver for Corsair keyboards and mice
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %patch -p1 < $pkgfiles/0001-We-use-systemd-don-t-check-for-this-file.patch
    mkdir build && cd build
    %cmake ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    # Safety symlink
    ln -s /usr/lib/systemd/systemd/ckb-next-daemon.service $installdir/usr/lib/systemd/system/ckb-daemon.service
    # Put udev bits in right place
    install -Dm00644 linux/udev/99-ckb-daemon.rules $installdir%libdir%/udev/rules.d/99-ckb-daemon.rules
    rm -rf $installdir/etc/
