name       : ckb
version    : 0.4.3
release    : 11
source     :
    - https://github.com/ckb-next/ckb-next/archive/v0.4.3.tar.gz : e4fbd14227ecc63fad9eaf705ca61defd7b44bcaa3ad29aae18cd8a69bbc9ef9
license    : GPL-2.0-or-later
component  : system.utils
homepage   : https://github.com/ckb-next/ckb-next/
summary    : An open-source driver for Corsair keyboards and mice
description: |
    ckb-next is an open-source driver for Corsair keyboards and mice. It aims to bring the features of Corsair's proprietary iCUE software to Linux operating systems.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(x11)
    - pkgconfig(xcb-ewmh)
setup      : |
    %patch -p1 < $pkgfiles/fix-segfault-when-creating-new-profile.patch

    mkdir build && cd build
    %cmake -DDISABLE_UPDATER=1 -DFORCE_INIT_SYSTEM="systemd" -DUDEV_RULE_DIRECTORY="%libdir%/udev/rules.d/" ..
build      : |
    %make -C build
install    : |
    %make_install -C build
    # Safety symlink
    ln -s /usr/lib/systemd/systemd/ckb-next-daemon.service $installdir/usr/lib/systemd/system/ckb-daemon.service
    rm -rf $installdir/etc/
