name       : ckb
version    : 0.2.9
release    : 5
source     :
    - git|https://github.com/ckb-next/ckb-next.git : v0.2.9
license    : GPL-2.0-only
component  : desktop.core
summary    : an open-source driver for Corsair keyboards and mice
description: |
    an open-source driver for Corsair keyboards and mice
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-installed-path-for-ckb-animations.patch
    %qmake -r ckb.pro
build      : |
    %make
install    : |
    install -D -m 00755 bin/ckb $installdir/usr/share/ckb/ckb
    install -D -m 00755 bin/ckb-daemon $installdir/usr/share/ckb/ckb-daemon
    install -d $installdir/usr/share/ckb/ckb-animations
    cp bin/ckb-animations/* $installdir/usr/share/ckb/ckb-animations

    install -d $installdir/usr/bin
    ln -s /usr/share/ckb/ckb $installdir/usr/bin/ckb
    ln -s /usr/share/ckb/ckb-daemon $installdir/usr/bin/ckb-daemon

    install -D -m 00644 usr/ckb.png $installdir/usr/share/icons/hicolor/512x512/apps/ckb.png
    install -D -m 00644 usr/ckb.desktop $installdir/usr/share/applications/ckb.desktop
    install -D -m 00644 service/systemd/ckb-daemon.service $installdir%libdir%/systemd/system/ckb-daemon.service
    install -D -m 00644 udev/99-ckb-daemon.rules $installdir%libdir%/udev/rules.d/99-ckb-daemon.rules
